apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapi-deployment
spec:
  selector:
    matchLabels:
      app: dockerapi-pod
  template:
    metadata:
      labels:
        app: dockerapi-pod
    spec:
      containers:
      - name: dockerapi-container
        image: nginx:alpine
        ports:
        - containerPort: 4242